### ISSUE TITLE
PCR-cDNA sequence from MinION not alligned

### ISSUE THREAD

**Issue by Macdot3** [nanoporetech/ont-minimap2#3]
Hello everyone, in my initial experiment, I aligned my cDNA sequence from ONT MinION using the following parameters:
`./minimap2 -ax map-ont /home/my_reference_PCR.fasta /home/input_pcr_PI4K.fastq > output_PI4K_aligned.sam`.  Then I built the bam file.
I noticed that the alignment focused only on a specific region of the reference with a 10X coverage. To examine other regions, I extracted the reads of maximum length from the fastq file using the following command:
`seqkit seq -m $(seqkit stats -T /home/input_pcr_PI4K.fastq | tail -n1 | cut -f 8) /home/input_pcr_PI4K.fastq -o /home/output_PI4K.fastq`
However, when aligning this new file using both the `-ax map-ont` and `-x splice` commands (since it's a cDNA sequence), I get 0% mapping according to samtools flagstats. I can't figure out why. Is there something wrong with the extraction or do I need to adjust the alignment parameters further? I hope you can help me.
Thanks a lot.

**Comment by tijyojwad** [comment]
Hi @Macdot3 - this may be a better question for https://github.com/lh3/minimap2
